-- MySQL Script generated by MySQL Workbench
-- qui 11 ago 2022 09:51:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toysdb_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toysdb_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toysdb_v2` ;
USE `toysdb_v2` ;

-- -----------------------------------------------------
-- Table `toysdb_v2`.`criancas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toysdb_v2`.`criancas` (
  `idcriancas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_criancas` VARCHAR(100) NOT NULL,
  `pai_criancas` VARCHAR(100) NOT NULL,
  `mae_criancas` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcriancas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toysdb_v2`.`brinquedos_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toysdb_v2`.`brinquedos_tipo` (
  `idbrinquedos_tipo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brinquedos_tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idbrinquedos_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toysdb_v2`.`brinquedos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toysdb_v2`.`brinquedos` (
  `idbrinquedos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_brinquedos` VARCHAR(100) NOT NULL,
  `tipo_brinquedos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idbrinquedos`),
  INDEX `fk_brinquedos_1_idx` (`tipo_brinquedos` ASC) VISIBLE,
  CONSTRAINT `fk_brinquedos_1`
    FOREIGN KEY (`tipo_brinquedos`)
    REFERENCES `toysdb_v2`.`brinquedos_tipo` (`idbrinquedos_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toysdb_v2`.`brinquedos_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toysdb_v2`.`brinquedos_detalhe` (
  `criancas_brinquedos_detalhe` INT UNSIGNED NOT NULL,
  `brinquedos_brinquedos_detalhe` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`criancas_brinquedos_detalhe`, `brinquedos_brinquedos_detalhe`),
  INDEX `fk_brinquedos_detalhe_2_idx` (`brinquedos_brinquedos_detalhe` ASC) VISIBLE,
  CONSTRAINT `fk_brinquedos_detalhe_1`
    FOREIGN KEY (`criancas_brinquedos_detalhe`)
    REFERENCES `toysdb_v2`.`criancas` (`idcriancas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brinquedos_detalhe_2`
    FOREIGN KEY (`brinquedos_brinquedos_detalhe`)
    REFERENCES `toysdb_v2`.`brinquedos` (`idbrinquedos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
